name: Test Execution with Maven and Allure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and run tests
        run: mvn clean test -DsuiteXmlFile=testng.xml

      - name: Install Allure Commandline
        if: always()
        run: |
          brew install allure || true   # (macOS runner) or
          sudo apt-get update && sudo apt-get install -y wget unzip
          wget -qO- https://github.com/allure-framework/allure2/releases/download/2.21.0/allure-2.21.0.zip > allure.zip
          unzip -o allure.zip -d $HOME/.allure
          echo "$HOME/.allure/allure-2.21.0/bin" >> $GITHUB_PATH

      - name: Generate Allure Report
        if: always()
        run: |
          allure generate allure-results --clean -o target/allure-report
      
      - name: Deploy Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/allure-report

      - name: Upload Allure Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/allure-report
